### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by marekventur**
- move UGFX into subtree
- add file that explains how to update it
- fix makefiles and gitignore
- comment out failing builds (we should fix those)
- add tilda board build

### CODE REVIEW

**Comment by dpslwk** [comment]
I think ugfx should actually be moved to the extmod/ folder along with the modugfx.[c|h] files from stmhal
this would be a little more in keeping with the way MP

**Comment by marekventur** [comment]
@dpslwk I've moved the subtree into extmod/ugfx. The modugfx.[c|h] I've left where they are, I'd rather we do that in a separate PR (if we really decide to do so)

**Comment by dpslwk** [comment]
Better but the build is still making a mess of where it puts the files and there not cleaned because of it
need to find a fix to go into this Makefile section

```
# for uGFX driver module
ifeq ($(MICROPY_PY_UGFX),1)
GFXLIB=../extmod/ugfx
include $(GFXLIB)/gfx.mk
include $(GFXLIB)/drivers/gdisp/ILI9341/driver.mk
INC += $(foreach d, $(GFXINC), -I$d)
SRC_C += modugfx.c
SRC_UGFX += $(GFXSRC)
SRC_C += ugfx_widgets.c
SRC_C += ugfx_containers.c
SRC_C += ugfx_styles.c
# Add Toggle driver
SRC_UGFX += ugfx_ginput_lld_toggle.c
endif
```

something on the INC and possible the SRC_UGFX lines

**Comment by marekventur** [comment]
@dpslwk that bit you posted is from the current makefile - what do you want me to do? I have no idea how to make that makefile less messy I'm afraid and I'd rather do that in a separate PR. For now I just want to get the build green.

**Comment by dpslwk** [comment]
there should be some way of moving the build output files around, posible by fixing the paths in SRC_UGFX so that when it builds ugfx its put in stmhal/build-%BOARD/extmod/ugfx

that would remove the need for the line in git ignore and also mean that ‘make clean’ removes the UGFX source

‘RepRap’ Matt

**Comment by marekventur** [comment]
I agree but a) I don't quite know how to do that atm and b) it's doing that already. It has nothing to do with the tests and I like to keep PRs as self-contained as possible.

It would be good to have this merged, it's getting a pain to comment out that "ugfx_list_detach_input" line every time :(

**Comment by dpslwk** [comment]
ok merge it, we need to raise an issue against the build dir and Makefile mess
‘RepRap’ Matt

**Pull request merged**
