### PR TITLE
wifi countrycode + enterprise authentication support

### PR DESCRIPTION
**Pull request by eqvinox**

### CODE REVIEW

**Comment by drrk** [comment]
This looks really good, I will test it all and get it merged soon.  Are you happy for it to pushed upstream too?

**Comment by eqvinox** [comment]
@drrk - sure, though the country code default should probably be made configurable for the target board.

**Comment by eqvinox** [comment]
@drrk btw, usage example is in https://github.com/emfcamp/Mk3-Firmware/pull/72 - the chip is really finicky about the CA certificate.

**Comment by drrk** [comment]
Yeah, I spent a lot of time working on WPA_ENT with the TI rep at the camp, and got it working, but it was too late for the event.  What you need is the final root, and it has to be in either DER or PEM format, and has to be /cert/ca.pem on the flash.  If it is in PEM format the chip converts it to DER.

It's also worth updating the service pack on the chip - I will post example code to the wiki.

**Comment by eqvinox** [comment]
@drrk ah, nice to get some info on the cert foobar... DER is smaller if nothing else. I shuffled the certificate around multiple times but wasn't quite sure what made it finally work. The python repo actually has the root + intermediate certs both in one file, which did work. I thought I tried root only and that didn't, but... not sure anymore. Changed it too often... :S

Funnily enough I installed the service pack before any other hacking, mostly because I wanted to see how that works :D (seems to be uncompressed ARM code divided into 3 sections with lots of crossreferences to ROM code)

**Comment by castaway** [comment]
get_mac doesnt match the API of the other available NICs, Im about to submit one that adds the whole ifconfig matching the micropython docs..

**Comment by drrk** [comment]
:+1:

**Pull request merged**
