### PR TITLE
L4 flash size

### PR DESCRIPTION
**Pull request by dpslwk**

### CODE REVIEW

**Comment by dpslwk** [comment]
the first commit could be cherry picked and sent upstream

**Comment by mattbrejza** [comment]
These lines need tweeking: 
https://github.com/emfcamp/micropython/pull/21/files#diff-12d02203b9909eecb9c2b992812f7d01R11
https://github.com/emfcamp/micropython/pull/21/files#diff-3383ca1ed8ccdd48b991594ed3ccd16fR11
should read ORIGIN = 0x08080000 not ORIGIN = 0x08020000

**Comment by dpslwk** [comment]
woops ill force push in a bit

‘RepRap’ Matt

**Comment by marekventur** [comment]
@dpslwk does this need merging?

**Comment by dpslwk** [comment]
Nope still needs some debugging

'RepRap' Matt

**Comment by dpslwk** [comment]
OK i've completely rewritten the way this is done to use a slip FS, which is how micropython did it for some of the other MCU's so fits quite nicely

**Pull request merged**
